In [2]:
import numpy as np

In [7]:
x=[[1,0,0],[0,1,0],[0,0,1],[np.sqrt(3.0)/2.0,np.sqrt(3.0)/2.0,np.sqrt(3.0)/2.0]]

In [6]:
x

[[1, 0, 0],
 [0, 1, 0],
 [0, 0, 1],
 [0.8660254037844386, 0.8660254037844386, 0.8660254037844386]]

Therefore 4 atoms lying in the plane perpendicular to <111> direction has been created, one each on the axes and one in the centre of a cube of unit size.

In [8]:
y=np.matrix(x)

In [9]:
y

matrix([[1.       , 0.       , 0.       ],
        [0.       , 1.       , 0.       ],
        [0.       , 0.       , 1.       ],
        [0.8660254, 0.8660254, 0.8660254]])

y is the matrix with the co-ordinates of teh four atoms. Now we do a SVD of y to interpret the SVD results

In [11]:
u, s, vh = np.linalg.svd(y, full_matrices=True, compute_uv=True)

In [12]:
u.shape, s.shape, vh.shape

((4, 4), (3,), (3, 3))

In [13]:
u

matrix([[ 3.20256308e-01, -5.55111512e-17,  8.16496581e-01,
         -4.80384461e-01],
        [ 3.20256308e-01,  7.07106781e-01, -4.08248290e-01,
         -4.80384461e-01],
        [ 3.20256308e-01, -7.07106781e-01, -4.08248290e-01,
         -4.80384461e-01],
        [ 8.32050294e-01,  1.11022302e-16, -4.99600361e-16,
          5.54700196e-01]])

In [14]:
s

array([1.80277564, 1.        , 1.        ])

In [15]:
vh

matrix([[ 0.57735027,  0.57735027,  0.57735027],
        [-0.        ,  0.70710678, -0.70710678],
        [ 0.81649658, -0.40824829, -0.40824829]])